--USE ReolMarked

CREATE TABLE SHELF_VENDOR (
	ShelfVendorID Int IDENTITY(1000,1) PRIMARY KEY,
	FirstName NVARChar(30) NOT NULL,
	LastName NVARChar(30) NOT NULL,
	PhoneNumber NVarChar(50) NOT NULL,
	Email NVarChar(50),
);

CREATE TABLE PAYMENT_METHOD(
	PaymentInfo NVarChar(30) PRIMARY KEY NOT NULL,
	ShelfVendorID Int NOT NULL,
	PaymentOption NVarChar(50) NOT NULL,

	CONSTRAINT FK_PAYMENTMETHOD_SHELFVENDOR FOREIGN KEY (ShelfVendorID) REFERENCES SHELF_VENDOR(ShelfVendorID)
);

CREATE TABLE RENT_AGREEMENT(
	RentAgreementID Int IDENTITY(1000,1) PRIMARY KEY,
	ShelfVendorID Int NOT NULL,
	StartDate Date NOT NULL,
	EndDate Date NOT NULL,

	CONSTRAINT FK_RENTAGREEMENT_SHELFVENDOR FOREIGN KEY (ShelfVendorID) REFERENCES SHELF_VENDOR(ShelfVendorID)
);

CREATE TABLE SHELF(
	ShelfNumber Int IDENTITY(1,1) PRIMARY KEY,
	RentAgreementID Int NULL,
	ShelfType NVarChar(40),
	Price decimal(6,2),

	CONSTRAINT FK_SHELF_RENTAGREEMENT FOREIGN KEY(RentAgreementID) REFERENCES RENT_AGREEMENT(RentAgreementID)
)

CREATE TABLE [TRANSACTION](
	TransactionID Int IDENTITY(1000,1) PRIMARY KEY,
	TransactionDate Date NOT NULL
);

CREATE TABLE [PRODUCT](
	ProductID Int IDENTITY(1000,1) PRIMARY KEY,
	ShelfNumber Int NOT NULL,
	ProductName NVarChar(100) NOT NULL,
	UnitPrice decimal(8,2) NOT NULL,
	Amount Int NOT NULL,

	CONSTRAINT FK_PRODUCT_SHELF FOREIGN KEY (ShelfNumber) REFERENCES SHELF(ShelfNumber)
);

CREATE TABLE TRANSACTION_PRODUCT(
	TransactionID Int NOT NULL,
	ProductID Int NOT NULL,
	UnitPrice decimal NOT NULL,
	Amount Int NOT NULL,

	CONSTRAINT FK_TRANSACTIONPRODUCT_TRANSACTION FOREIGN KEY (TransactionID) REFERENCES [TRANSACTION](TransactionID),
	CONSTRAINT FK_TRANSACTIONPRODUCT_PRODUCT FOREIGN KEY (ProductID) REFERENCES [PRODUCT](ProductID)
);